---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: pages
  label: Resource Pages
  create: documents
  match: "**/*"
  exclude: cpt.md
  new_doc_ext: md
- type: directory
  path: guidelines
  label: Guidelines
  create: all
  match: "**/*"
- type: directory
  path: styles
  label: Styles
  create: all
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: components
  label: Author Components
  create: all
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: components-dev
  label: Developer Components
  create: all
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: wp-theme
  label: Wordpress Theme
  create: all
  match: "**/*"
  new_doc_ext: md
upload_dir: assets
public_path: "/assets"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --full-index --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    -d _site
