---
label: Default
hide_body: false
fields:
- type: text
  name: layout
  label: layout
  default: page
  config:
    required: true
- type: text
  name: title
  label: title
- type: text
  name: description
  label: description
- type: text
  name: permalink
  label: permalink
- name: group
  type: text
  config:
    required: false
  label: Group
  description: which group does this page belong to?
